[package]
name = "nonorust"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
flexi_logger = "0.31.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4.27"
rustc-hash = "2.1.1"
clap = { version = "4.5.41", features = ["derive"] }

